version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: my-postgres-container
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
